version: '2'
services:
  mariadb:
    image: mysql/mysql-server:5.5
    environment:
      MYSQL_ROOT_PASSWORD: A-Ed)HXrNMQw}U,!
      MYSQL_USER: engage
      MYSQL_PASSWORD: engage
      MYSQL_DATABASE: engage
    stdin_open: true
    volumes:
    - /data/mysql:/var/lib/mysql
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=symlinux08.newdevops.net
  mysql-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=symlinux08.newdevops.net
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'

